apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "waf.fullname" . }}-modsecurity-rules
data:
  crs-setup.conf: |
    # OWASP CRS configuration
    SecAction \
      "id:900000,\
      phase:1,\
      nolog,\
      pass,\
      t:none,\
      setvar:tx.crs_setup_version=340"
    
    # Default actions
    SecDefaultAction "phase:1,log,auditlog,pass"
    SecDefaultAction "phase:2,log,auditlog,pass"
    
    # Paranoia level (1-4)
    SecAction \
      "id:900000,\
      phase:1,\
      nolog,\
      pass,\
      t:none,\
      setvar:tx.paranoia_level=1"
    
    # Rule exclusions
    SecRule REQUEST_URI "@beginsWith /api/" \
      "id:1000,\
      phase:1,\
      pass,\
      nolog,\
      ctl:ruleRemoveTargetById=941100-941999;ARGS:json,\
      ctl:ruleRemoveTargetById=942100-942999;ARGS:json"