{{- if .Values.waf.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "waf.fullname" . }}-tls
  labels:
    {{- include "waf.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.waf.tls.certificate.crt | b64enc }}
  tls.key: {{ .Values.waf.tls.certificate.key | b64enc }}
{{- end }}