{{- if .Values.waf.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "waf.serviceAccountName" . }}
  labels:
    {{- include "waf.labels" . | nindent 4 }}
  {{- with .Values.waf.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}