apiVersion: v1
kind: Service
metadata:
  name: {{ include "waf.fullname" . }}
  labels:
    {{- include "waf.labels" . | nindent 4 }}
  {{- with .Values.waf.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.waf.service.type }}
  ports:
    - port: {{ .Values.waf.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.waf.serviceHttps.port }}
      targetPort: https
      protocol: TCP
      name: https
    {{- if .Values.monitoring.enabled }}
    - port: 9113
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "waf.selectorLabels" . | nindent 4 }}
---
# Service for HTTPS traffic
apiVersion: v1
kind: Service
metadata:
  name: {{ include "waf.fullname" . }}-https
  labels:
    {{- include "waf.labels" . | nindent 4 }}
    app.kubernetes.io/component: https
  {{- with .Values.waf.serviceHttps.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.waf.serviceHttps.type }}
  ports:
    - port: {{ .Values.waf.serviceHttps.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "waf.selectorLabels" . | nindent 4 }} 