{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "waf.fullname" . }}-monitor
  labels:
    {{- include "waf.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "waf.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.monitoring.serviceMonitor.path }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      honorLabels: true
      # Additional scrape configuration
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'nginx_.*'
          action: keep
        - sourceLabels: [__name__]
          regex: 'waf_.*'
          action: keep
        - sourceLabels: [__name__]
          regex: 'modsecurity_.*'
          action: keep
      # Relabeling rules
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
          action: keep
          regex: {{ include "waf.fullname" . }}
        - sourceLabels: [__meta_kubernetes_namespace]
          action: replace
          targetLabel: kubernetes_namespace
        - sourceLabels: [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: kubernetes_pod_name
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
          action: replace
          targetLabel: app_instance
{{- end }} 