apiVersion: v2
name: waf
description: A production-grade Web Application Firewall for Kubernetes
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: cert-manager
    version: v1.13.0
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
keywords:
  - waf
  - security
  - nginx
  - modsecurity
  - kubernetes
home: https://github.com/yourusername/kubernetes-waf
sources:
  - https://github.com/yourusername/kubernetes-waf
maintainers:
  - name: Your Name
    email: your.email@example.com