name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint Helm Chart
      uses: helm/chart-testing-action@v2.3.1
      with:
        command: lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0
    - name: Install dependencies
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo add jetstack https://charts.jetstack.io
        helm repo update
    - name: Run Helm tests
      run: |
        helm dependency update charts/waf
        helm template charts/waf --set cert-manager.enabled=false | kubeval --strict
        helm template charts/waf --set cert-manager.enabled=false --set modsecurity.enabled=false | kubeval --strict

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Run security checks
      run: |
        docker run --rm -v "$(pwd):/app" aquasec/trivy:0.34.0 config /app
        docker run --rm -v "$(pwd)/charts/waf:/app" zegl/kube-score:v1.16.1 score /app